### PR TITLE
Extract common methods

### LINKED ISSUE #26: Extract common methods into a utility class
Methods such as cleaning text can be all put into a utility class

### PR DESCRIPTION
**Pull request by frankfka**
# Pull Request

## Description

Give a brief description of your changes:

Started extracting common methods into a util file

## Testing

If testing this change requires extra setup, please document it here:

New tests added for util class

## Ticket(s)

Closes #26

### CODE REVIEW

**Comment by kriscupofty** [comment]
What about putting the util file in a new utilities directory? We will need more than 1 util files for different models.

**Comment by r614** [comment]
> What about putting the util file in a new utilities directory? We will need more than 1 util files for different models.

I think it should be fine to have one base util file to initially process the text. As long as all of our models take the same argument, (string of text), I think that more processing can be done inside the model itself, especially if each class processes the string differently. Won't adding individual util files not make much of a difference?

**Comment by frankfka** [comment]
> 
> 
> What about putting the util file in a new utilities directory? We will need more than 1 util files for different models.

Yeah I talked to @rwblickhan about this. If we have enough methods we may have a directory for them, but for util methods that are specific for each individual model, they would be a private method in the model class.

**Comment by rwblickhan** [comment]
Yeah, I definitely see the argument for putting them into a separate directory, but for now I think it's small enough not to bother - we can always refactor later.

**Pull request merged**
