### PR TITLE
Trump Tweets data

### PR DESCRIPTION
**Pull request by jackattackyang**
# Pull Request

## Description

Twitter API was pretty disappointing and only allows 200 of the most recent tweets. Kind of went overboard but this Selenium script scrapes tweets from each day on the [Twitter Advanced Search](https://twitter.com/search-advanced?lang=en&lang=en&lang=en&lang=en&lang=en) page.

**Timeline:** June 2016 to Present &mdash; a little more than Trump's presidency
**Notes:**
- Text file is about 500KB, roughly 100k words. 
- Tweets are pretty selective: anything containing links or pictures were barred; this should have reduced the number of retweets that are not actually his own words or false positives.
- There are some repeated texts

## Ticket(s)

Affects #2

### CODE REVIEW

**Comment by jackattackyang** [comment]
Is it failing the pycodestyle? If so, is the proper approach to read the error message and manually adjust?

**Comment by rwblickhan** [comment]
Yep, that's correct. Also note that you should be able to run it locally with `pipenv run pycodestyle .` (or replace `.` with the path to the file you want to check). Unfortunately, unlike say `gofmt` or `rustfmt`, I don't believe `pycodestyle` will automatically fix issues for you (though there might be another tool for that).

**Comment by jackattackyang** [comment]
Gotcha thanks! I'll patch it up soon.

**Comment by jackattackyang** [comment]
🔥 Bless. For some reason some of the checks aren't showing up locally.

**Pull request merged**
